spring:
  application:
    name: store
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  supported-currencies: USD,EUR,GBP
  timeout: 1000
payment-gateway: paypal
port: 5761
host: https://smtp.gmail.com